### ISSUE TITLE
Task gets not resolved - no image uploaded

### ISSUE THREAD

**Issue by flauschtrud** [nintra/hoodie-plugin-imagine#1]
I just tried out the plugin and have a problem.

When I add an image there is a directory with an id created in my images folder, but it remains empty. In my user's db there's an unfinished task with the according objectId.

I come as far as to my "progress" callback but the task never gets resolved.

The plugin configuration is complete and there are no error messages.

Any hint to what I could have done wrong or where I could start looking for a solution?

**Comment by nintra** [comment]
Many things in this plugin have been changed. I am going to update
everything tomorrow. Sry,  for the inconvenience. :/

**Comment by nintra** [comment]
So, I added authorization. It can now be used in production I guess. The plugin doesn't use tasks anymore. Because tasks were saved by couchdb and kept in history, it quickly bloated up the user dbs and stopped hoodie from functioning.
That's why I decided to go for simple http requests instead. 

Just install the newest version and it should work. If there is still something wrong, please let me know :)

**Comment by flauschtrud** [comment]
Thanks for the fast answer and updates!

Still having problems though, but I'm not quite sure what's the problem.

I get the following errors:

```
POST http://127.0.0.1:6001/_api/_plugins/imagine/_api/image-upload 404 (Not Found)k.cors.a.crossDomain.send @ jquery.js:8630n.extend.ajax @ jquery.js:816622.exports.request @ hoodie.js:811815.exports.request @ hoodie.js:670231.Hoodie.extend.createTask @ hoodie.js:9830(anonymous function) @ hoodie.js:987753../promise @ hoodie.js:11937
```

```
HoodieError {name: "HoodieConnectionError", message: "Could not connect to Hoodie server at /.", url: "/"}
```

What did I miss?
I tried to enable cors for couchdb, but that didn't work either.

Btw: I did not quite understand about the problem with the tasks that you mentioned. When the tasks finish successful they should be cleared from the db anyway, shouldn't they?

**Comment by nintra** [comment]
can you please post the part of your code that is responsible for the
error. what hoodie version do you use. i am currently running an older
version: 0.6.3. (before the big changes) I haven't tested this plugin with
newer versions.

**Comment by flauschtrud** [comment]
Yes, I'm also using the stable version 0.6.3.

data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD/4

I'm calling hoodie.imagine.add with the dataUrl `data:image/jpeg;base64,/9j/4AAQSkZJRgABA...`:

```
hoodie.imagine.add('profile', dataUrl)
                            .progress(function (image) {
                                console.log('everything's fine here...');
                            })
                            .done(function (image) {
                                console.log('never arrived here...');
                            })
                            .fail(function (error) {
                                console.error('the image could not be saved');
                                console.error(error);
                            });
```

**Comment by nintra** [comment]
With a different dataUrl your code snippet worked fine for me. Your example dataUrl is broken.

You do not have any warnings in the developer console or on the server side?

**Comment by nintra** [comment]
There must be a response from the server in the network panel of the developer console. What does it say? Are you using a signed in User?

**Comment by flauschtrud** [comment]
Yeah, I cut the dataUrl off for posting here ;)

Yes, I'm signed in.

I'm getting the client-side error like described above. There's the 404 for `http://127.0.0.1:6001/_api/_plugins/imagine/_api/image-upload`

Here are my request and response headers.

```
POST /_api/_plugins/imagine/_api/image-upload HTTP/1.1
Host: 127.0.0.1:6001
Connection: keep-alive
Content-Length: 24332
Authorization: Bearer dXNlci9qYW5hOjU2MzdDNTkwOopGhJWGP0ZqYN6-MSTWYCswZCrM
Origin: http://127.0.0.1:6001
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/44.0.2403.89 Chrome/44.0.2403.89 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Accept: application/json, text/javascript, */*; q=0.01
X-Requested-With: XMLHttpRequest
Referer: http://127.0.0.1:6001/
Accept-Encoding: gzip, deflate
Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
```

```
HTTP/1.1 404 Not Found
vary: origin
access-control-allow-origin: http://127.0.0.1:6001
access-control-max-age: 86400
access-control-allow-methods: GET, HEAD, POST, PUT, PATCH, DELETE, OPTIONS
access-control-allow-headers: Authorization, Content-Type, If-None-Match
access-control-expose-headers: WWW-Authenticate, Server-Authorization
cache-control: no-cache
content-length: 0
Date: Mon, 02 Nov 2015 20:26:14 GMT
Connection: keep-alive
```

Since I get a jQuery error related to cors I think there's the problem. But I don't know what I have to configure different.

**Comment by nintra** [comment]
Wouldn't you receive a different error if it is cors related? Actually you should access the url from the same host. Is your script running on 127.0.0.1:6001? Or is it something else?

can you open the url in your browser? 
http://127.0.0.1:6001/_api/_plugins/imagine/_api/image-upload
it should say: method not allowed

**Comment by flauschtrud** [comment]
Yes, it says so.

**Comment by nintra** [comment]
And your script is running on the same host and port? 127.0.0.1:6001

**Comment by flauschtrud** [comment]
Yes.

**Comment by nintra** [comment]
running this in your console/code gives you an 'unauthorized' error?

```
$.ajax({ url: 'http://127.0.0.1:6001/_api/_plugins/imagine/_api/image-upload', type: 'POST' });
```

**Comment by flauschtrud** [comment]
Yes, again.

**Comment by nintra** [comment]
That means that there is no CORS problem and that I am out of ideas. :/ Maybe try to run your code in a fresh clean hoodie project.

If you still want to experiment with the CORS stuff, you can change the host by setting the environment constant `HOODIE_BIND_ADDRESS` to something else before running hoodie.

**Comment by flauschtrud** [comment]
:/ Clean hoodie project did not help.

I will give it a rest for now. If you have any new ideas please let me know :)

**Comment by flauschtrud** [comment]
Just had a look at my project again and after an update to your latest version I don't get the error anymore and can successfully upload an image :)

**Comment by nintra** [comment]
That's awesome! =)
If you need my help again - don't hesitate. I am using it in a mobile app.
(soon in production)
Am 19.02.2016 16:53 schrieb "JanaFlauschata" notifications@github.com:
